// eslint-disable-next-line camelcase
import { Montserrat, DM_Sans } from "next/font/google";

import "../styles/globals.css";
import Footer from "../components/Footer";
import { cn } from "../lib/utils";

export const montserrat = Montserrat({
  subsets: ["latin"],
  style: "normal",
  weight: ["400", "600", "700", "800"],
  variable: "--font-montserrat",
});

export const dmSans = DM_Sans({
  subsets: ["latin"],
  style: "normal",
  weight: "300",
  variable: "--font-sans",
});

export const metadata = {
  title: "Doctor Little Smiles",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className="scrollbar-thin scrollbar-track-light-grey scrollbar-thumb-light-blue scrollbar-thumb-rounded-full"
    >
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          dmSans.variable,
          montserrat.variable,
        )}
        suppressHydrationWarning
      >
        {children}
        <Footer />
        <script async src="https://player.vimeo.com/api/player.js" />
      </body>
    </html>
  );
}
