import { Inter as FontSans } from 'next/font/google'

import '../styles/globals.css'
import Footer from '../components/Footer'
import { cn } from '../lib/utils'

export const fontSans = FontSans({ subsets: ['latin'], variable: "--font-sans", })

export const metadata = {
  title: 'Doctor Little Smiles',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body  className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}>{children}<Footer/></body>
    </html>
  )
}
